### ISSUE TITLE
Support fetching authenticated user's posts

### ISSUE THREAD

**Issue by thebaer** [writeas/writeas-go#5]
## Overview
Add `GetPosts()` function to `user.go` that returns the authenticated user's posts.

## Implementation
This method requires user authentication.

[API documentation](https://developers.write.as/docs/api/?go#retrieve-user-39-s-posts).

**Comment by abhinav** [comment]
Looks like this is done but unreleased. https://github.com/writeas/go-writeas/blob/b7c23e245e770d52ac8d4a0a54a488ee6090f53b/post.go#L212

**Comment by thebaer** [comment]
@abhinav That's correct, thanks!
