### ISSUE TITLE
Overriding base URL

### ISSUE THREAD

**Issue by abhinav** [writeas/writeas-go#8]
## Overview

The library has 3 hard-coded URLs for the API service. It should probably
support changing the URL for testing and to allow users to point the client to
their own instance of WriteFreely.

## Implementation

Rather than add another parameter to the constructors (thus breaking the API),
I propose adding a `NewClientWith(Config) *Client` constructor where `Config`
is a struct with a bunch of optional fields. This will also allow adding other
new optional parameters for client configuration in the future without
breaking the API.

**Comment by thebaer** [comment]
Great idea. I started on a [library](https://code.as/core/api/src/branch/master) a while ago that might be able to do just this today, and would work for future libraries (e.g. `go-snapas`, `go-jotas`, etc.)

**Comment by abhinav** [comment]
Resolved by #9.
